project_id = "ejqsaloqrczyfiqljcym"

[functions.send-whatsapp]
verify_jwt = false

[functions.test-zapi]
verify_jwt = false

[functions.check-secrets]
verify_jwt = false

[functions.simple-test]
verify_jwt = false